# Generated by Django 5.1.3 on 2024-12-07 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_fist_name_customer_first_name_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='store_custo_last_na_2e448d_idx',
            old_name='store_custo_last_na_e6a359_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='store_customer',
        ),
    ]
